// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://chkxosydyukdcratdonz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNoa3hvc3lkeXVrZGNyYXRkb256Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEyODY5NTEsImV4cCI6MjA1Njg2Mjk1MX0.-EcyJ3iJl-Wwjtk_nFlskd_PmvkWY9QDJFxwCtE4qLU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);